---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dungewar.
--- DateTime: 6/3/2025 10:14 AM
---
local milk_pumpjack_item = table.deepcopy(data.raw["item"]["pumpjack"])

milk_pumpjack_item.name = "milk-pumpjack"

milk_pumpjack_item.stack_size = 10
milk_pumpjack_item.place_result = "milk-pumpjack"
milk_pumpjack_item.icon = "__cheesetorio__/graphics/icons/milk-pumpjack.png"

local cheese_item = {
    type = "item",
    name = "base-cheese",
    stack_size = 100,
}

data:extend({ milk_pumpjack_item, cheese_item })